// Supabase Edge Function "shop-admin" — ONE FILE, ready to paste into the dashboard editor.
// GENERATED by scripts/build-dashboard-functions.mjs from supabase/functions/. Do not edit here:
// change the sources, run `npm run build:functions`, and paste the new file.
// Deploy: Supabase → Edge Functions → Deploy a new function → Via Editor → name it "shop-admin",
// replace the editor's contents with this whole file, deploy, then turn OFF "Verify JWT".
// Setup and secrets: supabase/SHOP.md.
// supabase/functions/_shared/db.ts
var DbError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
  }
  status;
};
function createDb(supabaseUrl, serviceKey, fetchFn = fetch) {
  const headers = { apikey: serviceKey, "Content-Type": "application/json" };
  if (serviceKey.startsWith("eyJ")) headers.Authorization = `Bearer ${serviceKey}`;
  const fail = async (res) => {
    let message = `db_${res.status}`;
    try {
      const body = await res.json();
      if (body && typeof body.message === "string") message = body.message;
    } catch {
    }
    return new DbError(message, res.status);
  };
  return {
    async rpc(name, args = {}) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/rpc/${name}`, { method: "POST", headers, body: JSON.stringify(args) });
      if (!res.ok) throw await fail(res);
      const text = await res.text();
      return text ? JSON.parse(text) : null;
    },
    async select(table, query) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/${table}?${query}`, { headers });
      if (!res.ok) throw await fail(res);
      return await res.json();
    }
  };
}
async function loadOrder(db, id) {
  if (!/^[0-9a-f-]{36}$/i.test(id)) return null;
  const rows = await db.select("shop_orders", `id=eq.${id}&select=*,shop_order_items(*)`);
  return rows[0] ?? null;
}

// supabase/functions/_shared/email.ts
function createResendMailer(opts) {
  const fetchFn = opts.fetch ?? fetch;
  return {
    configured: Boolean(opts.apiKey),
    async send(to, msg) {
      const res = await fetchFn("https://api.resend.com/emails", {
        method: "POST",
        headers: { Authorization: `Bearer ${opts.apiKey}`, "Content-Type": "application/json" },
        body: JSON.stringify({ from: opts.from, to: [to], reply_to: opts.replyTo || void 0, subject: msg.subject, html: msg.html, text: msg.text })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.message ?? `resend_${res.status}`);
      return { id: data.id ?? "" };
    }
  };
}
var esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
var money = (cents) => `$${((cents ?? 0) / 100).toFixed(2)}`;
var orderLabel = (o) => o.order_number ? `#${o.order_number}` : "";
var firstName = (o) => (o.customer_name ?? o.shipping_name ?? "").trim().split(/\s+/)[0] ?? "";
function addressLines(name, a) {
  if (!a) return [];
  return [
    name ?? "",
    a.line1 ?? "",
    a.line2 ?? "",
    [a.city, [a.state, a.postal_code].filter(Boolean).join(" ")].filter(Boolean).join(", "),
    a.country && a.country !== "US" ? a.country : ""
  ].filter((l) => l.trim());
}
function trackingLink(carrier, tracking, explicit) {
  if (explicit && /^https:\/\//.test(explicit)) return explicit;
  if (!tracking) return null;
  const n = encodeURIComponent(tracking.replace(/\s+/g, ""));
  switch ((carrier ?? "").trim().toLowerCase()) {
    case "usps":
      return `https://tools.usps.com/go/TrackConfirmAction?tLabels=${n}`;
    case "ups":
      return `https://www.ups.com/track?tracknum=${n}`;
    case "fedex":
      return `https://www.fedex.com/fedextrack/?trknbr=${n}`;
    default:
      return null;
  }
}
var p = (text) => ({ html: `<p style="margin:0 0 16px">${esc(text)}</p>`, text });
var heading = (text) => ({
  html: `<p style="margin:28px 0 8px;font-size:11px;font-weight:600;letter-spacing:0.2em;text-transform:uppercase">${esc(text)}</p>`,
  text: `
${text.toUpperCase()}`
});
var link = (label, href) => ({
  html: `<p style="margin:0 0 16px"><a href="${esc(href)}" style="color:#545454;font-weight:600">${esc(label)}</a></p>`,
  text: `${label}: ${href}`
});
var lines = (ls) => ({ html: `<p style="margin:0 0 16px">${ls.map(esc).join("<br>")}</p>`, text: ls.join("\n") });
function summary(o) {
  const rows = o.shop_order_items.map((i) => [`${i.product_name} × ${i.quantity}`, money(i.unit_price_cents * i.quantity)]);
  rows.push(["Subtotal", money(o.subtotal_cents)]);
  if (o.discount_cents) rows.push(["Discount", `−${money(o.discount_cents)}`]);
  rows.push([o.shipping_method ? `Shipping (${o.shipping_method})` : "Shipping", money(o.shipping_cents)]);
  if (o.tax_cents) rows.push(["Tax", money(o.tax_cents)]);
  rows.push(["Total paid", money(o.total_cents)]);
  const last = rows.length - 1;
  return {
    html: '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin:0 0 16px">' + rows.map(
      ([a, b], i) => `<tr><td style="padding:8px 0;border-bottom:1px solid #c8c8c8${i === last ? ";font-weight:700" : ""}">${esc(a)}</td><td align="right" style="padding:8px 0;border-bottom:1px solid #c8c8c8${i === last ? ";font-weight:700" : ""}">${esc(b)}</td></tr>`
    ).join("") + "</table>",
    text: rows.map(([a, b]) => `${a}: ${b}`).join("\n")
  };
}
function companionBlocks(siteUrl) {
  return [
    heading("Your cleaning companion"),
    p(
      "Your calendar comes with the free cleaning companion website. It shows today’s small Daily Reset and the one area of the house to focus on, matching the cleaning zone printed on your calendar."
    ),
    p("Scan the QR code printed on your calendar with your phone’s camera, or open it here. No account, no subscription, nothing to install."),
    link("Open the cleaning companion", `${siteUrl}/app`)
  ];
}
function layout(siteUrl, title, blocks, replyTo) {
  const all = [...blocks, ...replyTo ? [p("Questions about your order? Just reply to this email.")] : []];
  const html = `<!doctype html><html><body style="margin:0;padding:0;background:#ffffff">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;font-family:Montserrat,Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#545454">
<tr><td style="padding:0 0 24px;border-bottom:2px solid #545454"><img src="${esc(siteUrl)}/brand/omc-badge-160.png" width="64" height="64" alt="Organized Mom Collective"></td></tr>
<tr><td style="padding:24px 0 0"><h1 style="margin:0 0 20px;font-size:24px;line-height:1.2;color:#545454">${esc(title)}</h1>
${all.map((b) => b.html).join("\n")}
</td></tr>
<tr><td style="padding:24px 0 0;border-top:1px solid #c8c8c8;font-size:12px;color:#666666">Organized Mom Collective · <a href="${esc(siteUrl)}" style="color:#666666">organizedmomcollective.com</a></td></tr>
</table></td></tr></table></body></html>`;
  const text = [title, "", ...all.map((b) => b.text), "", `Organized Mom Collective · ${siteUrl}`].join("\n");
  return { html, text };
}
function renderEmail(kind, o, opts) {
  const msg = renderBody(kind, o, opts);
  return o.livemode === false ? { ...msg, subject: `[Test] ${msg.subject}` } : msg;
}
function renderBody(kind, o, opts) {
  const n = orderLabel(o);
  const hi = firstName(o);
  const ship = addressLines(o.shipping_name, o.shipping_address);
  switch (kind) {
    case "confirmation": {
      const m = layout(
        opts.siteUrl,
        hi ? `Thank you, ${hi}. Your order is confirmed.` : "Thank you. Your order is confirmed.",
        [
          p(`Order ${n} · paid ${money(o.total_cents)}. This email is your receipt.`),
          summary(o),
          ...ship.length ? [heading("Shipping to"), lines(ship)] : [],
          heading("What happens next"),
          p("We pack each order by hand. When yours ships, we’ll email you the tracking number."),
          ...companionBlocks(opts.siteUrl)
        ],
        opts.replyTo
      );
      return { ...m, subject: `Your Organized Mom Collective order ${n}` };
    }
    case "shipped": {
      const url = trackingLink(o.carrier, o.tracking_number, o.tracking_url);
      const m = layout(
        opts.siteUrl,
        `Your order ${n} is on its way`,
        [
          p(hi ? `Good news, ${hi}: your calendar has shipped.` : "Good news: your calendar has shipped."),
          lines([o.carrier ? `Carrier: ${o.carrier}` : "", o.tracking_number ? `Tracking number: ${o.tracking_number}` : ""].filter(Boolean)),
          ...url ? [link("Track your package", url)] : [],
          ...ship.length ? [heading("Shipping to"), lines(ship)] : [],
          ...companionBlocks(opts.siteUrl)
        ],
        opts.replyTo
      );
      return { ...m, subject: `Your order ${n} has shipped` };
    }
    case "refund": {
      const full = o.payment_status === "refunded";
      const canceled = full && o.fulfillment_status === "canceled";
      const amount = opts.refundCents ?? o.refunded_cents;
      const m = layout(
        opts.siteUrl,
        canceled ? `Your order ${n} has been canceled` : `We’ve refunded ${money(amount)} for order ${n}`,
        [
          p(
            canceled ? `Your order has been canceled and refunded in full: ${money(o.refunded_cents)} back to your original payment method.` : `${money(amount)} is on its way back to your original payment method.${full ? "" : ` Total refunded so far: ${money(o.refunded_cents)}.`}`
          ),
          p("Refunds usually take 5–10 business days to appear, depending on your bank.")
        ],
        opts.replyTo
      );
      return { ...m, subject: canceled ? `Order ${n} canceled and refunded` : `Refund for order ${n}` };
    }
    case "access": {
      const m = layout(
        opts.siteUrl,
        "How to use your cleaning companion",
        [
          p(hi ? `Hi ${hi}, here’s how to open the cleaning companion that comes with your calendar.` : "Here’s how to open the cleaning companion that comes with your calendar."),
          link("Open the cleaning companion", `${opts.siteUrl}/app`),
          p("Or scan the QR code printed on your calendar with your phone’s camera. It opens on Today: a small Daily Reset and one area of the house to focus on."),
          p("It’s free with your calendar. No account, no subscription, nothing to install. Your checkmarks are saved in your phone’s browser, and you can add it to your Home Screen from Settings."),
          link("See how it works", `${opts.siteUrl}/companion`)
        ],
        opts.replyTo
      );
      return { ...m, subject: "Your cleaning companion: how to get started" };
    }
  }
}
async function deliverEmail(deps, orderId, kind, key, extra = {}) {
  try {
    const order = await loadOrder(deps.db, orderId);
    if (!order?.email) return "no_email";
    const claim = await deps.db.rpc("shop_email_claim", { p_order: orderId, p_kind: kind, p_key: key, p_to: order.email });
    if (claim == null) return "duplicate";
    if (!deps.mailer.configured) {
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "skipped", p_provider_id: null, p_error: "Email provider not configured" });
      return "skipped";
    }
    try {
      const { id } = await deps.mailer.send(order.email, renderEmail(kind, order, { siteUrl: deps.siteUrl, replyTo: deps.replyTo, ...extra }));
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "sent", p_provider_id: id, p_error: null });
      return "sent";
    } catch (err) {
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "failed", p_provider_id: null, p_error: err.message });
      return "failed";
    }
  } catch (err) {
    console.error("email", kind, orderId, err);
    return "failed";
  }
}

// supabase/functions/_shared/env.ts
var STRIPE_API_VERSION = "2025-03-31.basil";
function readEnv(get) {
  const v = (k, fallback = "") => (get(k) ?? fallback).trim();
  const siteUrl = v("SHOP_SITE_URL", "https://organizedmomcollective.com").replace(/\/$/, "");
  const origins = v("SHOP_ALLOWED_ORIGINS");
  return {
    supabaseUrl: v("SUPABASE_URL").replace(/\/$/, ""),
    serviceRoleKey: v("SUPABASE_SERVICE_ROLE_KEY"),
    anonKey: v("SUPABASE_ANON_KEY"),
    stripeSecretKey: v("STRIPE_SECRET_KEY"),
    stripeWebhookSecret: v("STRIPE_WEBHOOK_SECRET"),
    liveCheckoutEnabled: v("SHOP_LIVE_CHECKOUT") === "enabled",
    siteUrl,
    allowedOrigins: origins ? origins.split(",").map((o) => o.trim().replace(/\/$/, "")).filter(Boolean) : [siteUrl],
    previewToken: v("SHOP_PREVIEW_TOKEN"),
    resendApiKey: v("RESEND_API_KEY"),
    emailFrom: v("SHOP_EMAIL_FROM", "Organized Mom Collective <orders@organizedmomcollective.com>"),
    emailReplyTo: v("SHOP_EMAIL_REPLY_TO")
  };
}

// supabase/functions/_shared/http.ts
function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", ...headers }
  });
}
function corsHeaders(req, allowed) {
  const origin = req.headers.get("origin");
  if (!origin || !allowed.includes(origin.replace(/\/$/, ""))) return {};
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, apikey, content-type, x-client-info, x-shop-preview",
    "Access-Control-Max-Age": "600",
    Vary: "Origin"
  };
}
async function readJson(req, maxBytes = 2e4) {
  const text = await req.text();
  if (text.length > maxBytes) return null;
  try {
    const body = JSON.parse(text);
    return body && typeof body === "object" && !Array.isArray(body) ? body : null;
  } catch {
    return null;
  }
}

// supabase/functions/_shared/stripe.ts
function stripeMode(key) {
  return /^(sk|rk)_live_/.test(key) ? "live" : "test";
}
var StripeError = class extends Error {
  constructor(message, status, code) {
    super(message);
    this.status = status;
    this.code = code;
  }
  status;
  code;
};
function formEncode(params) {
  const out = new URLSearchParams();
  const add = (key, value) => {
    if (value === null || value === void 0) return;
    if (Array.isArray(value)) value.forEach((v, i) => add(`${key}[${i}]`, v));
    else if (typeof value === "object") for (const [k, v] of Object.entries(value)) add(`${key}[${k}]`, v);
    else out.append(key, String(value));
  };
  for (const [k, v] of Object.entries(params)) add(k, v);
  return out.toString();
}
function createStripe(opts) {
  const base = opts.apiBase ?? "https://api.stripe.com";
  const fetchFn = opts.fetch ?? fetch;
  return {
    mode: stripeMode(opts.secretKey),
    async request(method, path, params = {}, idempotencyKey) {
      const body = formEncode(params);
      const headers = {
        Authorization: `Bearer ${opts.secretKey}`,
        "Stripe-Version": opts.apiVersion
      };
      if (method === "POST") headers["Content-Type"] = "application/x-www-form-urlencoded";
      if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
      const url = method === "GET" && body ? `${base}${path}?${body}` : `${base}${path}`;
      const res = await fetchFn(url, { method, headers, body: method === "POST" ? body : void 0 });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        const err = data.error;
        throw new StripeError(err?.message ?? `stripe_${res.status}`, res.status, err?.code);
      }
      return data;
    }
  };
}

// supabase/functions/_shared/deps.ts
function depsFromEnv(get, fetchFn = fetch) {
  const env = readEnv(get);
  return {
    env,
    db: createDb(env.supabaseUrl, env.serviceRoleKey, fetchFn),
    stripe: createStripe({ secretKey: env.stripeSecretKey, apiVersion: STRIPE_API_VERSION, fetch: fetchFn }),
    mailer: createResendMailer({ apiKey: env.resendApiKey, from: env.emailFrom, replyTo: env.emailReplyTo, fetch: fetchFn }),
    fetch: fetchFn,
    now: () => Math.floor(Date.now() / 1e3)
  };
}
function stripeBlockedReason(deps) {
  if (!deps.env.stripeSecretKey) return "stripe_not_configured";
  if (!/^(sk|rk)_(test|live)_/.test(deps.env.stripeSecretKey)) return "stripe_not_configured";
  if (deps.stripe.mode === "live" && !deps.env.liveCheckoutEnabled) return "live_checkout_disabled";
  return null;
}
var emailDeps = (deps) => ({
  db: deps.db,
  mailer: deps.mailer,
  siteUrl: deps.env.siteUrl,
  replyTo: Boolean(deps.env.emailReplyTo)
});

// supabase/functions/_shared/handlers/webhook.ts
async function applyRefund(deps, paymentIntent, refundedTotal, actor) {
  const r = await deps.db.rpc("shop_apply_refund", {
    p_payment_intent: paymentIntent,
    p_refunded_cents: refundedTotal,
    p_actor: actor
  });
  if (r.found && r.transitioned && r.order_id) {
    await deliverEmail(emailDeps(deps), r.order_id, "refund", `refund:${r.order_id}:${refundedTotal}`, { refundCents: r.amount_cents });
  }
  return r;
}

// supabase/functions/_shared/handlers/admin.ts
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
  status;
};
var UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var uuid = (v) => {
  if (typeof v !== "string" || !UUID.test(v)) throw new HttpError(400, "invalid_id");
  return v;
};
var str = (v, max = 500) => typeof v === "string" ? v.slice(0, max) : null;
async function authenticate(deps, req) {
  const token = req.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1];
  if (!token) throw new HttpError(401, "unauthorized");
  const res = await deps.fetch(`${deps.env.supabaseUrl}/auth/v1/user`, {
    headers: { apikey: deps.env.anonKey || deps.env.serviceRoleKey, Authorization: `Bearer ${token}` }
  });
  if (!res.ok) throw new HttpError(401, "unauthorized");
  const user = await res.json();
  if (!user.id || !UUID.test(user.id)) throw new HttpError(401, "unauthorized");
  const ok = await deps.db.rpc("shop_is_admin_user", { p_user: user.id });
  if (!ok) throw new HttpError(403, "forbidden");
  return { id: user.id, email: user.email ?? user.id };
}
function createAdminHandler(deps) {
  return async (req) => {
    const cors = corsHeaders(req, deps.env.allowedOrigins);
    if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
    if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405, cors);
    try {
      const admin = await authenticate(deps, req);
      const body = await readJson(req);
      if (!body) throw new HttpError(400, "invalid_request");
      return json(await run(deps, admin, body), 200, cors);
    } catch (err) {
      if (err instanceof HttpError) return json({ error: err.message }, err.status, cors);
      if (err instanceof DbError && err.status < 500) return json({ error: err.message }, 400, cors);
      console.error("shop-admin", err);
      return json({ error: "server_error" }, 500, cors);
    }
  };
}
async function run(deps, admin, b) {
  const actor = `admin:${admin.email}`;
  switch (b.action) {
    case "whoami":
      return { email: admin.email };
    case "status": {
      const [settings] = await deps.db.select("shop_settings", "select=checkout_mode,tax_mode");
      const rates = await deps.db.select("shop_shipping_rates", "select=test_only&active=is.true");
      const mode = deps.stripe.mode;
      const liveRates = rates.filter((r) => !r.test_only).length;
      const flag = deps.env.liveCheckoutEnabled;
      return {
        stripe_mode: deps.env.stripeSecretKey ? mode : null,
        live_checkout_flag: flag,
        webhook_secret_set: Boolean(deps.env.stripeWebhookSecret),
        preview_token_set: Boolean(deps.env.previewToken),
        email_configured: deps.mailer.configured,
        reply_to_set: Boolean(deps.env.emailReplyTo),
        checkout_mode: settings?.checkout_mode ?? null,
        tax_mode: settings?.tax_mode ?? null,
        live_shipping_rates: liveRates,
        test_shipping_rates: rates.length - liveRates,
        // What would happen right now for someone on /checkout without the preview token.
        public_checkout_open: settings?.checkout_mode === "live" && flag && stripeBlockedReason(deps) === null && (mode === "test" || liveRates > 0),
        real_payments_possible: mode === "live" && flag && settings?.checkout_mode === "live" && liveRates > 0
      };
    }
    case "fulfillment": {
      const id = uuid(b.order_id);
      const status = str(b.status, 20);
      await deps.db.rpc("shop_set_fulfillment", {
        p_order: id,
        p_status: status,
        p_carrier: str(b.carrier, 60),
        p_tracking: str(b.tracking_number, 100),
        p_tracking_url: str(b.tracking_url, 500),
        p_actor: actor
      });
      let email = null;
      if (status === "shipped" && b.notify === true) {
        const o = await loadOrder(deps.db, id);
        email = await deliverEmail(emailDeps(deps), id, "shipped", `shipped:${id}:${o?.tracking_number ?? "none"}`);
      }
      return { ok: true, email };
    }
    case "refund": {
      const blocked = stripeBlockedReason(deps);
      if (blocked) throw new HttpError(503, blocked);
      const id = uuid(b.order_id);
      const requestId = str(b.request_id, 64);
      if (!requestId || !/^[A-Za-z0-9-]{8,64}$/.test(requestId)) throw new HttpError(400, "request_id_required");
      const o = await loadOrder(deps.db, id);
      if (!o) throw new HttpError(404, "not_found");
      if (o.payment_status !== "paid" && o.payment_status !== "partially_refunded") throw new HttpError(409, "not_refundable");
      if (!o.stripe_payment_intent_id) throw new HttpError(409, "no_payment_to_refund");
      const remaining = (o.total_cents ?? 0) - o.refunded_cents;
      const amount = b.amount_cents == null ? remaining : Number(b.amount_cents);
      if (!Number.isInteger(amount) || amount < 1 || amount > remaining) throw new HttpError(400, "invalid_amount");
      const refund = await deps.stripe.request(
        "POST",
        "/v1/refunds",
        { payment_intent: o.stripe_payment_intent_id, amount, reason: "requested_by_customer", metadata: { order_id: id } },
        `refund:${id}:${requestId}`
      );
      if (refund.status === "failed" || refund.status === "canceled") throw new HttpError(502, "refund_failed");
      const chargeId = typeof refund.charge === "string" ? refund.charge : refund.charge.id;
      const charge = await deps.stripe.request("GET", `/v1/charges/${chargeId}`);
      await applyRefund(deps, o.stripe_payment_intent_id, charge.amount_refunded, actor);
      const restocked = b.restock === true ? await deps.db.rpc("shop_restock_order", { p_order: id, p_actor: actor }) : 0;
      return { ok: true, refund_id: refund.id, refund_status: refund.status, restocked };
    }
    case "restock": {
      const id = uuid(b.order_id);
      const o = await loadOrder(deps.db, id);
      if (!o) throw new HttpError(404, "not_found");
      if (o.payment_status !== "refunded" && o.payment_status !== "partially_refunded") throw new HttpError(409, "refund_first");
      return { ok: true, restocked: await deps.db.rpc("shop_restock_order", { p_order: id, p_actor: actor }) };
    }
    case "resend_email": {
      const id = uuid(b.order_id);
      const kind = b.kind;
      if (!["confirmation", "shipped", "refund", "access"].includes(kind)) throw new HttpError(400, "invalid_kind");
      const o = await loadOrder(deps.db, id);
      if (!o) throw new HttpError(404, "not_found");
      if (o.payment_status === "pending" || o.payment_status === "expired" || o.payment_status === "canceled" || o.payment_status === "failed") {
        throw new HttpError(409, "not_paid");
      }
      if (kind === "shipped" && o.fulfillment_status !== "shipped" && o.fulfillment_status !== "delivered") throw new HttpError(409, "not_shipped");
      if (kind === "refund" && o.refunded_cents === 0) throw new HttpError(409, "not_refunded");
      const email = await deliverEmail(emailDeps(deps), id, kind, `${kind}:${id}:resend:${Date.now()}`);
      return { ok: email === "sent" || email === "skipped", email };
    }
    case "note":
      await deps.db.rpc("shop_set_note", { p_order: uuid(b.order_id), p_note: str(b.note, 4e3) ?? "", p_actor: actor });
      return { ok: true };
    case "stock": {
      const delta = b.delta == null ? null : Number(b.delta);
      const set = b.set == null ? null : Number(b.set);
      if (delta === null === (set === null)) throw new HttpError(400, "delta_or_set");
      if (delta !== null && !Number.isInteger(delta) || set !== null && (!Number.isInteger(set) || set < 0)) throw new HttpError(400, "invalid_amount");
      const stock = await deps.db.rpc("shop_adjust_stock", {
        p_product: uuid(b.product_id),
        p_delta: delta,
        p_set: set,
        p_reason: str(b.reason, 200),
        p_actor: actor
      });
      return { ok: true, stock };
    }
    case "product": {
      const f = b.fields ?? {};
      const allowed = ["name", "edition", "description", "details", "price_cents", "images", "active", "max_per_order", "sort"];
      const fields = Object.fromEntries(Object.entries(f).filter(([k]) => allowed.includes(k)));
      if ("images" in fields) {
        const imgs = fields.images;
        const okImgs = Array.isArray(imgs) && imgs.length <= 8 && imgs.every(
          (i) => i && typeof i === "object" && typeof i.src === "string" && /^(\/(?!\/)[A-Za-z0-9/_.-]+|https:\/\/[^\s"'<>]+)$/.test(i.src) && typeof i.alt === "string" && i.alt.trim()
        );
        if (!okImgs) throw new HttpError(400, "invalid_images");
      }
      if ("details" in fields && !(Array.isArray(fields.details) && fields.details.every((d) => typeof d === "string" && d.length <= 200))) {
        throw new HttpError(400, "invalid_details");
      }
      await deps.db.rpc("shop_update_product", { p_product: uuid(b.product_id), p: fields });
      return { ok: true };
    }
    case "settings": {
      const f = b.fields ?? {};
      const allowed = ["checkout_mode", "tax_mode", "product_tax_code", "checkout_minutes", "max_checkouts_per_hour"];
      await deps.db.rpc("shop_update_settings", { p: Object.fromEntries(Object.entries(f).filter(([k]) => allowed.includes(k))) });
      return { ok: true };
    }
    case "shipping_rate": {
      const r = b.rate ?? {};
      const allowed = ["id", "label", "amount_cents", "min_days", "max_days", "active", "test_only", "sort"];
      return { ok: true, id: await deps.db.rpc("shop_save_shipping_rate", { p: Object.fromEntries(Object.entries(r).filter(([k]) => allowed.includes(k))) }) };
    }
    default:
      throw new HttpError(400, "unknown_action");
  }
}

// supabase/shop-admin/index.ts
Deno.serve(createAdminHandler(depsFromEnv((key) => Deno.env.get(key))));
