// Supabase Edge Function "shop-checkout" — ONE FILE, ready to paste into the dashboard editor.
// GENERATED by scripts/build-dashboard-functions.mjs from supabase/functions/. Do not edit here:
// change the sources, run `npm run build:functions`, and paste the new file.
// Deploy: Supabase → Edge Functions → Deploy a new function → Via Editor → name it "shop-checkout",
// replace the editor's contents with this whole file, deploy, then turn OFF "Verify JWT".
// Setup and secrets: supabase/SHOP.md.
// supabase/functions/_shared/db.ts
var DbError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
  }
  status;
};
function createDb(supabaseUrl, serviceKey, fetchFn = fetch) {
  const headers = { apikey: serviceKey, "Content-Type": "application/json" };
  if (serviceKey.startsWith("eyJ")) headers.Authorization = `Bearer ${serviceKey}`;
  const fail = async (res) => {
    let message = `db_${res.status}`;
    try {
      const body = await res.json();
      if (body && typeof body.message === "string") message = body.message;
    } catch {
    }
    return new DbError(message, res.status);
  };
  return {
    async rpc(name, args = {}) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/rpc/${name}`, { method: "POST", headers, body: JSON.stringify(args) });
      if (!res.ok) throw await fail(res);
      const text = await res.text();
      return text ? JSON.parse(text) : null;
    },
    async select(table, query) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/${table}?${query}`, { headers });
      if (!res.ok) throw await fail(res);
      return await res.json();
    }
  };
}

// supabase/functions/_shared/email.ts
function createResendMailer(opts) {
  const fetchFn = opts.fetch ?? fetch;
  return {
    configured: Boolean(opts.apiKey),
    async send(to, msg, idempotencyKey) {
      const res = await fetchFn("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${opts.apiKey}`,
          "Content-Type": "application/json",
          ...idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {}
        },
        body: JSON.stringify({ from: opts.from, to: [to], reply_to: opts.replyTo || void 0, subject: msg.subject, html: msg.html, text: msg.text })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.message ?? `resend_${res.status}`);
      return { id: data.id ?? "" };
    }
  };
}

// supabase/functions/_shared/env.ts
var STRIPE_API_VERSION = "2025-03-31.basil";
function readEnv(get) {
  const v = (k, fallback = "") => (get(k) ?? fallback).trim();
  const siteUrl = v("SHOP_SITE_URL", "https://organizedmomcollective.com").replace(/\/$/, "");
  const origins = v("SHOP_ALLOWED_ORIGINS");
  return {
    supabaseUrl: v("SUPABASE_URL").replace(/\/$/, ""),
    serviceRoleKey: v("SUPABASE_SERVICE_ROLE_KEY"),
    anonKey: v("SUPABASE_ANON_KEY"),
    stripeSecretKey: v("STRIPE_SECRET_KEY"),
    stripeWebhookSecret: v("STRIPE_WEBHOOK_SECRET"),
    liveCheckoutEnabled: v("SHOP_LIVE_CHECKOUT") === "enabled",
    siteUrl,
    allowedOrigins: origins ? origins.split(",").map((o) => o.trim().replace(/\/$/, "")).filter(Boolean) : [siteUrl],
    previewToken: v("SHOP_PREVIEW_TOKEN"),
    resendApiKey: v("RESEND_API_KEY"),
    emailFrom: v("SHOP_EMAIL_FROM", "Organized Mom Collective <orders@organizedmomcollective.com>"),
    emailReplyTo: v("SHOP_EMAIL_REPLY_TO")
  };
}

// supabase/functions/_shared/http.ts
function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", ...headers }
  });
}
function corsHeaders(req, allowed) {
  const origin = req.headers.get("origin");
  if (!origin || !allowed.includes(origin.replace(/\/$/, ""))) return {};
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, apikey, content-type, x-client-info, x-shop-preview",
    "Access-Control-Max-Age": "600",
    Vary: "Origin"
  };
}
function clientIp(req) {
  const fwd = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim();
  return fwd || req.headers.get("cf-connecting-ip") || req.headers.get("x-real-ip") || "unknown";
}
function safeEqual(a, b) {
  const enc = new TextEncoder();
  const x = enc.encode(a);
  const y = enc.encode(b);
  let diff = x.length ^ y.length;
  for (let i = 0; i < Math.max(x.length, y.length); i++) diff |= (x[i] ?? 0) ^ (y[i] ?? 0);
  return diff === 0;
}
async function readJson(req, maxBytes = 2e4) {
  const text = await req.text();
  if (text.length > maxBytes) return null;
  try {
    const body = JSON.parse(text);
    return body && typeof body === "object" && !Array.isArray(body) ? body : null;
  } catch {
    return null;
  }
}

// supabase/functions/_shared/stripe.ts
function stripeMode(key) {
  return /^(sk|rk)_live_/.test(key) ? "live" : "test";
}
var StripeError = class extends Error {
  constructor(message, status, code) {
    super(message);
    this.status = status;
    this.code = code;
  }
  status;
  code;
};
function formEncode(params) {
  const out = new URLSearchParams();
  const add = (key, value) => {
    if (value === null || value === void 0) return;
    if (Array.isArray(value)) value.forEach((v, i) => add(`${key}[${i}]`, v));
    else if (typeof value === "object") for (const [k, v] of Object.entries(value)) add(`${key}[${k}]`, v);
    else out.append(key, String(value));
  };
  for (const [k, v] of Object.entries(params)) add(k, v);
  return out.toString();
}
function createStripe(opts) {
  const base = opts.apiBase ?? "https://api.stripe.com";
  const fetchFn = opts.fetch ?? fetch;
  return {
    mode: stripeMode(opts.secretKey),
    async request(method, path, params = {}, idempotencyKey) {
      const body = formEncode(params);
      const headers = {
        Authorization: `Bearer ${opts.secretKey}`,
        "Stripe-Version": opts.apiVersion
      };
      if (method === "POST") headers["Content-Type"] = "application/x-www-form-urlencoded";
      if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
      const url = method === "GET" && body ? `${base}${path}?${body}` : `${base}${path}`;
      const res = await fetchFn(url, { method, headers, body: method === "POST" ? body : void 0 });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        const err = data.error;
        throw new StripeError(err?.message ?? `stripe_${res.status}`, res.status, err?.code);
      }
      return data;
    }
  };
}

// supabase/functions/_shared/deps.ts
function depsFromEnv(get, fetchFn = fetch) {
  const env = readEnv(get);
  return {
    env,
    db: createDb(env.supabaseUrl, env.serviceRoleKey, fetchFn),
    stripe: createStripe({ secretKey: env.stripeSecretKey, apiVersion: STRIPE_API_VERSION, fetch: fetchFn }),
    mailer: createResendMailer({ apiKey: env.resendApiKey, from: env.emailFrom, replyTo: env.emailReplyTo, fetch: fetchFn }),
    fetch: fetchFn,
    now: () => Math.floor(Date.now() / 1e3)
  };
}
function stripeBlockedReason(deps) {
  if (!deps.env.stripeSecretKey) return "stripe_not_configured";
  if (!/^(sk|rk)_(test|live)_/.test(deps.env.stripeSecretKey)) return "stripe_not_configured";
  if (deps.stripe.mode === "live" && !deps.env.liveCheckoutEnabled) return "live_checkout_disabled";
  return null;
}

// supabase/functions/_shared/checkout.ts
var SHIPPING_TAX_CODE = "txcd_92010001";
var absolute = (src, siteUrl) => /^https:\/\//.test(src) ? src : `${siteUrl}${src.startsWith("/") ? "" : "/"}${src}`;
function sessionParams(order, opts) {
  const automatic = order.tax_mode === "automatic";
  return {
    mode: "payment",
    ui_mode: "embedded",
    return_url: `${opts.siteUrl}/checkout/complete?session_id={CHECKOUT_SESSION_ID}`,
    client_reference_id: order.order_id,
    metadata: { order_id: order.order_id },
    payment_intent_data: { metadata: { order_id: order.order_id }, description: "Organized Mom Collective order" },
    // Cards, plus Apple Pay and Google Pay (wallets ride on the card method).
    payment_method_types: ["card"],
    line_items: order.items.map((i) => ({
      quantity: i.quantity,
      price_data: {
        currency: "usd",
        unit_amount: i.unit_price_cents,
        tax_behavior: "exclusive",
        product_data: {
          name: i.edition ? `${i.name} (${i.edition})` : i.name,
          images: i.image ? [absolute(i.image, opts.siteUrl)] : void 0,
          tax_code: automatic ? order.product_tax_code : void 0,
          metadata: { slug: i.slug }
        }
      },
      dynamic_tax_rates: opts.taxRateIds.length ? opts.taxRateIds : void 0
    })),
    shipping_address_collection: { allowed_countries: ["US"] },
    shipping_options: order.shipping_rates.slice(0, 5).map((r) => ({
      shipping_rate_data: {
        type: "fixed_amount",
        display_name: r.label,
        fixed_amount: { amount: r.amount_cents, currency: "usd" },
        tax_behavior: "exclusive",
        tax_code: automatic ? SHIPPING_TAX_CODE : void 0,
        delivery_estimate: r.min_days || r.max_days ? {
          minimum: r.min_days ? { unit: "business_day", value: r.min_days } : void 0,
          maximum: r.max_days ? { unit: "business_day", value: r.max_days } : void 0
        } : void 0
      }
    })),
    automatic_tax: { enabled: automatic },
    allow_promotion_codes: true,
    billing_address_collection: "auto",
    customer_creation: "if_required",
    submit_type: "pay",
    expires_at: opts.nowSeconds + order.checkout_minutes * 60
  };
}
function parseCart(raw) {
  if (!Array.isArray(raw) || raw.length < 1 || raw.length > 10) return null;
  const out = [];
  for (const line of raw) {
    if (!line || typeof line !== "object") return null;
    const { slug, quantity } = line;
    if (typeof slug !== "string" || !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug) || slug.length > 80) return null;
    if (typeof quantity !== "number" || !Number.isInteger(quantity) || quantity < 1 || quantity > 50) return null;
    out.push({ slug, quantity });
  }
  return out;
}
function checkoutError(message) {
  const [code, slug] = message.split(":");
  switch (code) {
    case "checkout_closed":
      return { status: 403, code };
    case "shipping_not_configured":
    case "tax_not_configured":
      return { status: 503, code };
    case "shipping_unavailable":
      return { status: 409, code };
    case "rate_limited":
      return { status: 429, code };
    case "sold_out":
    case "unavailable":
    case "too_many":
      return { status: 409, code, slug };
    case "invalid_cart":
      return { status: 400, code };
    default:
      return { status: 500, code: "server_error" };
  }
}

// supabase/functions/_shared/handlers/checkout.ts
function createCheckoutHandler(deps) {
  return async (req) => {
    const cors = corsHeaders(req, deps.env.allowedOrigins);
    if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
    if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405, cors);
    const body = await readJson(req);
    if (!body) return json({ error: "invalid_request" }, 400, cors);
    const blocked = stripeBlockedReason(deps);
    if (blocked) return json({ error: blocked }, 503, cors);
    try {
      if (body.action === "cancel") return json(await cancel(deps, body.session_id), 200, cors);
      if (body.action !== "create") return json({ error: "invalid_request" }, 400, cors);
      const cart = parseCart(body.items);
      if (!cart) return json({ error: "invalid_cart" }, 400, cors);
      const header = req.headers.get("x-shop-preview") ?? "";
      const preview = Boolean(deps.env.previewToken) && safeEqual(header, deps.env.previewToken);
      const result = await create(deps, cart, clientIp(req), preview);
      return json(result.body, result.status, cors);
    } catch (err) {
      console.error("shop-checkout", err);
      return json({ error: "server_error" }, 500, cors);
    }
  };
}
async function create(deps, cart, ip, preview) {
  let order;
  try {
    order = await deps.db.rpc("shop_create_order", {
      p_items: cart,
      p_client: ip,
      p_preview: preview,
      p_livemode: deps.stripe.mode === "live",
      p_public_allowed: deps.env.liveCheckoutEnabled
    });
  } catch (err) {
    if (err instanceof DbError) {
      const e = checkoutError(err.message);
      if (e.code !== "server_error") return { status: e.status, body: { error: e.code, slug: e.slug } };
    }
    throw err;
  }
  try {
    if (order.shipping_rates.length === 0) throw new Error("no_shipping_rates");
    const taxRateIds = order.tax_mode === "manual" ? await stripeTaxRates(deps, order) : [];
    const session = await deps.stripe.request(
      "POST",
      "/v1/checkout/sessions",
      sessionParams(order, { siteUrl: deps.env.siteUrl, nowSeconds: deps.now(), taxRateIds }),
      `checkout:${order.order_id}`
    );
    await deps.db.rpc("shop_attach_session", { p_order: order.order_id, p_session: session.id, p_livemode: session.livemode });
    return { status: 200, body: { client_secret: session.client_secret, session_id: session.id } };
  } catch (err) {
    console.error("shop-checkout: could not open Stripe checkout", err);
    await deps.db.rpc("shop_cancel_checkout", { p_order: order.order_id, p_reason: err.message.slice(0, 200) });
    return { status: 502, body: { error: "payment_unavailable" } };
  }
}
async function stripeTaxRates(deps, order) {
  const ids = [];
  for (const rate of order.tax_rates) {
    let id = rate.stripe_ids?.[deps.stripe.mode];
    if (!id) {
      const created = await deps.stripe.request(
        "POST",
        "/v1/tax_rates",
        {
          display_name: rate.label,
          percentage: Number(rate.percentage),
          inclusive: false,
          country: "US",
          state: rate.state,
          jurisdiction: rate.state,
          tax_type: "sales_tax"
        },
        `tax-rate:${rate.state}:${rate.percentage}`
      );
      id = created.id;
      await deps.db.rpc("shop_cache_tax_rate", { p_state: rate.state, p_mode: deps.stripe.mode, p_stripe_id: id });
    }
    ids.push(id);
  }
  return ids;
}
async function cancel(deps, sessionId) {
  if (typeof sessionId !== "string" || !/^cs_(test|live)_[A-Za-z0-9]{10,200}$/.test(sessionId)) return { canceled: false };
  const [order] = await deps.db.select(
    "shop_orders",
    `stripe_session_id=eq.${encodeURIComponent(sessionId)}&select=id,payment_status`
  );
  if (!order || order.payment_status !== "pending") return { canceled: false };
  try {
    const s = await deps.stripe.request("POST", `/v1/checkout/sessions/${sessionId}/expire`);
    if (s.status !== "expired") return { canceled: false };
  } catch {
    return { canceled: false };
  }
  const r = await deps.db.rpc("shop_checkout_ended", {
    p_session: sessionId,
    p_status: "expired",
    p_detail: { via: "customer_left" }
  });
  return { canceled: Boolean(r?.transitioned) };
}

// supabase/shop-checkout/index.ts
Deno.serve(createCheckoutHandler(depsFromEnv((key) => Deno.env.get(key))));
