// Supabase Edge Function "stripe-webhook" — ONE FILE, ready to paste into the dashboard editor.
// GENERATED by scripts/build-dashboard-functions.mjs from supabase/functions/. Do not edit here:
// change the sources, run `npm run build:functions`, and paste the new file.
// Deploy: Supabase → Edge Functions → Deploy a new function → Via Editor → name it "stripe-webhook",
// replace the editor's contents with this whole file, deploy, then turn OFF "Verify JWT".
// Setup and secrets: supabase/SHOP.md.
// supabase/functions/_shared/db.ts
var DbError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
  }
  status;
};
function createDb(supabaseUrl, serviceKey, fetchFn = fetch) {
  const headers = { apikey: serviceKey, "Content-Type": "application/json" };
  if (serviceKey.startsWith("eyJ")) headers.Authorization = `Bearer ${serviceKey}`;
  const fail = async (res) => {
    let message = `db_${res.status}`;
    try {
      const body = await res.json();
      if (body && typeof body.message === "string") message = body.message;
    } catch {
    }
    return new DbError(message, res.status);
  };
  return {
    async rpc(name, args = {}) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/rpc/${name}`, { method: "POST", headers, body: JSON.stringify(args) });
      if (!res.ok) throw await fail(res);
      const text = await res.text();
      return text ? JSON.parse(text) : null;
    },
    async select(table, query) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/${table}?${query}`, { headers });
      if (!res.ok) throw await fail(res);
      return await res.json();
    }
  };
}
async function loadOrder(db, id) {
  if (!/^[0-9a-f-]{36}$/i.test(id)) return null;
  const rows = await db.select("shop_orders", `id=eq.${id}&select=*,shop_order_items(*)`);
  return rows[0] ?? null;
}

// supabase/functions/_shared/email.ts
function createResendMailer(opts) {
  const fetchFn = opts.fetch ?? fetch;
  return {
    configured: Boolean(opts.apiKey),
    async send(to, msg, idempotencyKey) {
      const res = await fetchFn("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${opts.apiKey}`,
          "Content-Type": "application/json",
          ...idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {}
        },
        body: JSON.stringify({ from: opts.from, to: [to], reply_to: opts.replyTo || void 0, subject: msg.subject, html: msg.html, text: msg.text })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.message ?? `resend_${res.status}`);
      return { id: data.id ?? "" };
    }
  };
}
var esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
var money = (cents) => `$${((cents ?? 0) / 100).toFixed(2)}`;
var orderLabel = (o) => o.order_number ? `#${o.order_number}` : "";
var firstName = (o) => (o.customer_name ?? o.shipping_name ?? "").trim().split(/\s+/)[0] ?? "";
function addressLines(name, a) {
  if (!a) return [];
  return [
    name ?? "",
    a.line1 ?? "",
    a.line2 ?? "",
    [a.city, [a.state, a.postal_code].filter(Boolean).join(" ")].filter(Boolean).join(", "),
    a.country && a.country !== "US" ? a.country : ""
  ].filter((l) => l.trim());
}
function trackingLink(carrier, tracking, explicit) {
  if (explicit && /^https:\/\//.test(explicit)) return explicit;
  if (!tracking) return null;
  const n = encodeURIComponent(tracking.replace(/\s+/g, ""));
  switch ((carrier ?? "").trim().toLowerCase()) {
    case "usps":
      return `https://tools.usps.com/go/TrackConfirmAction?tLabels=${n}`;
    case "ups":
      return `https://www.ups.com/track?tracknum=${n}`;
    case "fedex":
      return `https://www.fedex.com/fedextrack/?trknbr=${n}`;
    default:
      return null;
  }
}
var p = (text) => ({ html: `<p style="margin:0 0 16px">${esc(text)}</p>`, text });
var heading = (text) => ({
  html: `<p style="margin:28px 0 8px;font-size:11px;font-weight:600;letter-spacing:0.2em;text-transform:uppercase">${esc(text)}</p>`,
  text: `
${text.toUpperCase()}`
});
var link = (label, href) => ({
  html: `<p style="margin:0 0 16px"><a href="${esc(href)}" style="color:#545454;font-weight:600">${esc(label)}</a></p>`,
  text: `${label}: ${href}`
});
var lines = (ls) => ({ html: `<p style="margin:0 0 16px">${ls.map(esc).join("<br>")}</p>`, text: ls.join("\n") });
function summary(o) {
  const rows = o.shop_order_items.map((i) => [`${i.product_name} × ${i.quantity}`, money(i.unit_price_cents * i.quantity)]);
  rows.push(["Subtotal", money(o.subtotal_cents)]);
  if (o.discount_cents) rows.push(["Discount", `−${money(o.discount_cents)}`]);
  rows.push([o.shipping_method ? `Shipping (${o.shipping_method})` : "Shipping", money(o.shipping_cents)]);
  if (o.tax_cents) rows.push(["Tax", money(o.tax_cents)]);
  rows.push(["Total paid", money(o.total_cents)]);
  const last = rows.length - 1;
  return {
    html: '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin:0 0 16px">' + rows.map(
      ([a, b], i) => `<tr><td style="padding:8px 0;border-bottom:1px solid #c8c8c8${i === last ? ";font-weight:700" : ""}">${esc(a)}</td><td align="right" style="padding:8px 0;border-bottom:1px solid #c8c8c8${i === last ? ";font-weight:700" : ""}">${esc(b)}</td></tr>`
    ).join("") + "</table>",
    text: rows.map(([a, b]) => `${a}: ${b}`).join("\n")
  };
}
function companionBlocks(siteUrl) {
  return [
    heading("Your cleaning companion"),
    p(
      "Your calendar comes with the free cleaning companion website. It shows today’s small Daily Reset and the one area of the house to focus on, matching the cleaning zone printed on your calendar."
    ),
    p("Scan the QR code printed on your calendar with your phone’s camera, or open it here. No account, no subscription, nothing to install."),
    link("Open the cleaning companion", `${siteUrl}/app`)
  ];
}
function layout(siteUrl, title, blocks, supportEmail) {
  const all = [...blocks, ...supportEmail ? [p(`Questions about your order? Reply to this email or write to ${supportEmail}.`)] : []];
  const html = `<!doctype html><html><body style="margin:0;padding:0;background:#ffffff">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;font-family:Montserrat,Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#545454">
<tr><td style="padding:0 0 24px;border-bottom:2px solid #545454"><img src="${esc(siteUrl)}/brand/omc-badge-160.png" width="64" height="64" alt="Organized Mom Collective"></td></tr>
<tr><td style="padding:24px 0 0"><h1 style="margin:0 0 20px;font-size:24px;line-height:1.2;color:#545454">${esc(title)}</h1>
${all.map((b) => b.html).join("\n")}
</td></tr>
<tr><td style="padding:24px 0 0;border-top:1px solid #c8c8c8;font-size:12px;color:#666666">Organized Mom Collective · <a href="${esc(siteUrl)}" style="color:#666666">organizedmomcollective.com</a></td></tr>
</table></td></tr></table></body></html>`;
  const text = [title, "", ...all.map((b) => b.text), "", `Organized Mom Collective · ${siteUrl}`].join("\n");
  return { html, text };
}
function renderEmail(kind, o, opts) {
  const msg = renderBody(kind, o, opts);
  return o.livemode === false ? { ...msg, subject: `[Test] ${msg.subject}` } : msg;
}
function renderBody(kind, o, opts) {
  const n = orderLabel(o);
  const hi = firstName(o);
  const ship = addressLines(o.shipping_name, o.shipping_address);
  switch (kind) {
    case "confirmation": {
      const m = layout(
        opts.siteUrl,
        hi ? `Thank you, ${hi}. Your order is confirmed.` : "Thank you. Your order is confirmed.",
        [
          p(`Order ${n} · paid ${money(o.total_cents)}. This email is your receipt.`),
          summary(o),
          ...ship.length ? [heading("Shipping to"), lines(ship)] : [],
          heading("What happens next"),
          p("We pack each order by hand. When yours ships, we’ll email you the tracking number."),
          ...companionBlocks(opts.siteUrl)
        ],
        opts.supportEmail
      );
      return { ...m, subject: `Your Organized Mom Collective order ${n}` };
    }
    case "shipped": {
      const url = trackingLink(o.carrier, o.tracking_number, o.tracking_url);
      const m = layout(
        opts.siteUrl,
        `Your order ${n} is on its way`,
        [
          p(hi ? `Good news, ${hi}: your calendar has shipped.` : "Good news: your calendar has shipped."),
          lines([o.carrier ? `Carrier: ${o.carrier}` : "", o.tracking_number ? `Tracking number: ${o.tracking_number}` : ""].filter(Boolean)),
          ...url ? [link("Track your package", url)] : [],
          ...ship.length ? [heading("Shipping to"), lines(ship)] : [],
          ...companionBlocks(opts.siteUrl)
        ],
        opts.supportEmail
      );
      return { ...m, subject: `Your order ${n} has shipped` };
    }
    case "refund": {
      const full = o.payment_status === "refunded";
      const canceled = full && o.fulfillment_status === "canceled";
      const amount = opts.refundCents ?? o.refunded_cents;
      const m = layout(
        opts.siteUrl,
        canceled ? `Your order ${n} has been canceled` : `We’ve refunded ${money(amount)} for order ${n}`,
        [
          p(
            canceled ? `Your order has been canceled and refunded in full: ${money(o.refunded_cents)} back to your original payment method.` : `${money(amount)} is on its way back to your original payment method.${full ? "" : ` Total refunded so far: ${money(o.refunded_cents)}.`}`
          ),
          p("Refunds usually take 5–10 business days to appear, depending on your bank.")
        ],
        opts.supportEmail
      );
      return { ...m, subject: canceled ? `Order ${n} canceled and refunded` : `Refund for order ${n}` };
    }
    case "access": {
      const m = layout(
        opts.siteUrl,
        "How to use your cleaning companion",
        [
          p(hi ? `Hi ${hi}, here’s how to open the cleaning companion that comes with your calendar.` : "Here’s how to open the cleaning companion that comes with your calendar."),
          link("Open the cleaning companion", `${opts.siteUrl}/app`),
          p("Or scan the QR code printed on your calendar with your phone’s camera. It opens on Today: a small Daily Reset and one area of the house to focus on."),
          p("It’s free with your calendar. No account, no subscription, nothing to install. Your checkmarks are saved in your phone’s browser, and you can add it to your Home Screen from Settings."),
          link("See how it works", `${opts.siteUrl}/companion`)
        ],
        opts.supportEmail
      );
      return { ...m, subject: "Your cleaning companion: how to get started" };
    }
  }
}
async function sha256Hex(text) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function deliverEmail(deps, orderId, kind, key, extra = {}) {
  try {
    const order = await loadOrder(deps.db, orderId);
    if (!order?.email) return "no_email";
    const claim = await deps.db.rpc("shop_email_claim", { p_order: orderId, p_kind: kind, p_key: key, p_to: order.email });
    if (claim == null) return "duplicate";
    if (!deps.mailer.configured) {
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "skipped", p_provider_id: null, p_error: "Email provider not configured" });
      return "skipped";
    }
    try {
      const msg = renderEmail(kind, order, { siteUrl: deps.siteUrl, supportEmail: deps.supportEmail, ...extra });
      const idem = `${key}/${(await sha256Hex(`${order.email}
${msg.subject}
${msg.text}`)).slice(0, 24)}`;
      const { id } = await deps.mailer.send(order.email, msg, idem.slice(0, 256));
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "sent", p_provider_id: id, p_error: null });
      return "sent";
    } catch (err) {
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "failed", p_provider_id: null, p_error: err.message });
      return "failed";
    }
  } catch (err) {
    console.error("email", kind, orderId, err);
    return "failed";
  }
}

// supabase/functions/_shared/env.ts
var STRIPE_API_VERSION = "2025-03-31.basil";
function readEnv(get) {
  const v = (k, fallback = "") => (get(k) ?? fallback).trim();
  const siteUrl = v("SHOP_SITE_URL", "https://organizedmomcollective.com").replace(/\/$/, "");
  const origins = v("SHOP_ALLOWED_ORIGINS");
  return {
    supabaseUrl: v("SUPABASE_URL").replace(/\/$/, ""),
    serviceRoleKey: v("SUPABASE_SERVICE_ROLE_KEY"),
    anonKey: v("SUPABASE_ANON_KEY"),
    stripeSecretKey: v("STRIPE_SECRET_KEY"),
    stripeWebhookSecret: v("STRIPE_WEBHOOK_SECRET"),
    liveCheckoutEnabled: v("SHOP_LIVE_CHECKOUT") === "enabled",
    siteUrl,
    allowedOrigins: origins ? origins.split(",").map((o) => o.trim().replace(/\/$/, "")).filter(Boolean) : [siteUrl],
    previewToken: v("SHOP_PREVIEW_TOKEN"),
    resendApiKey: v("RESEND_API_KEY"),
    emailFrom: v("SHOP_EMAIL_FROM", "Organized Mom Collective <orders@organizedmomcollective.com>"),
    emailReplyTo: v("SHOP_EMAIL_REPLY_TO")
  };
}

// supabase/functions/_shared/http.ts
function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", ...headers }
  });
}
function safeEqual(a, b) {
  const enc = new TextEncoder();
  const x = enc.encode(a);
  const y = enc.encode(b);
  let diff = x.length ^ y.length;
  for (let i = 0; i < Math.max(x.length, y.length); i++) diff |= (x[i] ?? 0) ^ (y[i] ?? 0);
  return diff === 0;
}

// supabase/functions/_shared/stripe.ts
function stripeMode(key) {
  return /^(sk|rk)_live_/.test(key) ? "live" : "test";
}
var StripeError = class extends Error {
  constructor(message, status, code) {
    super(message);
    this.status = status;
    this.code = code;
  }
  status;
  code;
};
function formEncode(params) {
  const out = new URLSearchParams();
  const add = (key, value) => {
    if (value === null || value === void 0) return;
    if (Array.isArray(value)) value.forEach((v, i) => add(`${key}[${i}]`, v));
    else if (typeof value === "object") for (const [k, v] of Object.entries(value)) add(`${key}[${k}]`, v);
    else out.append(key, String(value));
  };
  for (const [k, v] of Object.entries(params)) add(k, v);
  return out.toString();
}
function createStripe(opts) {
  const base = opts.apiBase ?? "https://api.stripe.com";
  const fetchFn = opts.fetch ?? fetch;
  return {
    mode: stripeMode(opts.secretKey),
    async request(method, path, params = {}, idempotencyKey) {
      const body = formEncode(params);
      const headers = {
        Authorization: `Bearer ${opts.secretKey}`,
        "Stripe-Version": opts.apiVersion
      };
      if (method === "POST") headers["Content-Type"] = "application/x-www-form-urlencoded";
      if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
      const url = method === "GET" && body ? `${base}${path}?${body}` : `${base}${path}`;
      const res = await fetchFn(url, { method, headers, body: method === "POST" ? body : void 0 });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        const err = data.error;
        throw new StripeError(err?.message ?? `stripe_${res.status}`, res.status, err?.code);
      }
      return data;
    }
  };
}
async function hmacHex(secret, payload) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(payload));
  return [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function verifyStripeSignature(payload, header, secret, nowSeconds = Math.floor(Date.now() / 1e3), toleranceSeconds = 300) {
  if (!header || !secret) return false;
  const parts = header.split(",").map((p2) => p2.split("="));
  const t = Number(parts.find(([k]) => k === "t")?.[1]);
  const v1 = parts.filter(([k]) => k === "v1").map(([, v]) => v);
  if (!Number.isFinite(t) || v1.length === 0) return false;
  if (Math.abs(nowSeconds - t) > toleranceSeconds) return false;
  const expected = await hmacHex(secret, `${t}.${payload}`);
  return v1.some((sig) => safeEqual(sig, expected));
}

// supabase/functions/_shared/deps.ts
function depsFromEnv(get, fetchFn = fetch) {
  const env = readEnv(get);
  return {
    env,
    db: createDb(env.supabaseUrl, env.serviceRoleKey, fetchFn),
    stripe: createStripe({ secretKey: env.stripeSecretKey, apiVersion: STRIPE_API_VERSION, fetch: fetchFn }),
    mailer: createResendMailer({ apiKey: env.resendApiKey, from: env.emailFrom, replyTo: env.emailReplyTo, fetch: fetchFn }),
    fetch: fetchFn,
    now: () => Math.floor(Date.now() / 1e3)
  };
}
function stripeBlockedReason(deps) {
  if (!deps.env.stripeSecretKey) return "stripe_not_configured";
  if (!/^(sk|rk)_(test|live)_/.test(deps.env.stripeSecretKey)) return "stripe_not_configured";
  if (deps.stripe.mode === "live" && !deps.env.liveCheckoutEnabled) return "live_checkout_disabled";
  return null;
}
var emailDeps = (deps) => ({
  db: deps.db,
  mailer: deps.mailer,
  siteUrl: deps.env.siteUrl,
  supportEmail: deps.env.emailReplyTo
});

// supabase/functions/_shared/checkout.ts
var isPaidSession = (s) => s.status === "complete" && (s.payment_status === "paid" || s.payment_status === "no_payment_required");
function promotionLabel(s) {
  const d = s.total_details?.breakdown?.discounts?.[0]?.discount;
  if (!d) return null;
  const promo = d.promotion_code;
  if (promo && typeof promo === "object" && promo.code) return promo.code;
  const coupon = d.coupon ?? d.source?.coupon;
  if (coupon && typeof coupon === "object") return coupon.name ?? coupon.id ?? null;
  if (typeof promo === "string") return promo;
  return typeof coupon === "string" ? coupon : null;
}
function paidOrderData(s) {
  const ship = s.collected_information?.shipping_details ?? s.shipping_details ?? null;
  const pi = typeof s.payment_intent === "string" ? s.payment_intent : s.payment_intent?.id ?? null;
  const rate = s.shipping_cost?.shipping_rate;
  const t = s.total_details ?? {};
  return {
    order_id: s.metadata?.order_id ?? s.client_reference_id ?? null,
    payment_intent: pi,
    livemode: Boolean(s.livemode),
    email: s.customer_details?.email ?? null,
    name: s.customer_details?.name ?? null,
    phone: s.customer_details?.phone ?? null,
    shipping_name: ship?.name ?? s.customer_details?.name ?? null,
    shipping_address: ship?.address ?? null,
    shipping_method: rate && typeof rate === "object" ? rate.display_name ?? null : null,
    promotion_code: promotionLabel(s),
    currency: s.currency ?? null,
    subtotal_cents: s.amount_subtotal ?? null,
    discount_cents: t.amount_discount ?? 0,
    shipping_cents: t.amount_shipping ?? s.shipping_cost?.amount_total ?? 0,
    tax_cents: t.amount_tax ?? 0,
    total_cents: s.amount_total ?? null
  };
}

// supabase/functions/_shared/handlers/webhook.ts
function createWebhookHandler(deps) {
  return async (req) => {
    if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
    const raw = await req.text();
    const valid = await verifyStripeSignature(raw, req.headers.get("stripe-signature"), deps.env.stripeWebhookSecret, deps.now());
    if (!valid) return json({ error: "invalid_signature" }, 400);
    let event;
    try {
      event = JSON.parse(raw);
    } catch {
      return json({ error: "invalid_payload" }, 400);
    }
    const blocked = stripeBlockedReason(deps);
    if (blocked) return json({ error: blocked }, 503);
    if (event.livemode !== (deps.stripe.mode === "live")) return json({ error: "mode_mismatch" }, 400);
    const state = await deps.db.rpc("shop_stripe_event_begin", { p_id: event.id, p_type: event.type });
    if (state === "done") return json({ received: true, duplicate: true });
    try {
      await handleEvent(deps, event);
      await deps.db.rpc("shop_stripe_event_done", { p_id: event.id });
      return json({ received: true });
    } catch (err) {
      console.error("stripe-webhook", event.type, event.id, err);
      return json({ error: "processing_failed" }, 500);
    }
  };
}
var idOf = (v) => typeof v === "string" ? v : v && typeof v === "object" && "id" in v ? String(v.id) : null;
async function handleEvent(deps, event) {
  const obj = event.data.object;
  if (event.type.startsWith("checkout.session.") && !/^cs_(test|live)_[A-Za-z0-9]{10,200}$/.test(String(obj.id))) return;
  switch (event.type) {
    case "checkout.session.completed":
    case "checkout.session.async_payment_succeeded": {
      const session = await deps.stripe.request("GET", `/v1/checkout/sessions/${obj.id}`, {
        expand: ["shipping_cost.shipping_rate", "total_details.breakdown"]
      });
      if (!isPaidSession(session)) return;
      const r = await deps.db.rpc("shop_mark_paid", { p_session: session.id, p: paidOrderData(session) });
      if (!r.found) {
        console.warn("stripe-webhook: paid session with no order", session.id);
        return;
      }
      await deliverEmail(emailDeps(deps), r.order_id, "confirmation", `confirmation:${r.order_id}`);
      return;
    }
    case "checkout.session.async_payment_failed":
    case "checkout.session.expired": {
      await deps.db.rpc("shop_checkout_ended", {
        p_session: obj.id,
        p_status: event.type === "checkout.session.expired" ? "expired" : "failed",
        p_detail: { event: event.id }
      });
      return;
    }
    case "payment_intent.payment_failed": {
      const err = obj.last_payment_error ?? {};
      await deps.db.rpc("shop_note_event", {
        p_order: obj.metadata?.order_id ?? null,
        p_payment_intent: obj.id,
        p_kind: "payment_failed",
        p_detail: { message: err.message ?? null, code: err.code ?? null, decline_code: err.decline_code ?? null },
        p_flag: null
      });
      return;
    }
    case "charge.refunded": {
      const pi = idOf(obj.payment_intent);
      if (!pi) return;
      await applyRefund(deps, pi, Number(obj.amount_refunded ?? 0), "stripe");
      return;
    }
    case "refund.failed": {
      await deps.db.rpc("shop_note_event", {
        p_order: obj.metadata?.order_id ?? null,
        p_payment_intent: idOf(obj.payment_intent),
        p_kind: "refund_failed",
        p_detail: { amount_cents: obj.amount ?? null, reason: obj.failure_reason ?? null },
        p_flag: "refund_failed"
      });
      return;
    }
    case "charge.dispute.created": {
      await deps.db.rpc("shop_note_event", {
        p_order: null,
        p_payment_intent: idOf(obj.payment_intent),
        p_kind: "dispute_opened",
        p_detail: { amount_cents: obj.amount ?? null, reason: obj.reason ?? null },
        p_flag: "disputed"
      });
      return;
    }
    default:
      return;
  }
}
async function applyRefund(deps, paymentIntent, refundedTotal, actor) {
  const r = await deps.db.rpc("shop_apply_refund", {
    p_payment_intent: paymentIntent,
    p_refunded_cents: refundedTotal,
    p_actor: actor
  });
  let email = null;
  if (r.found && r.order_id) {
    const key = `refund:${r.order_id}:${refundedTotal}`;
    if (r.transitioned) {
      email = await deliverEmail(emailDeps(deps), r.order_id, "refund", key, { refundCents: r.amount_cents });
    } else {
      const [row] = await deps.db.select("shop_email_log", `dedupe_key=eq.${encodeURIComponent(key)}&select=status`);
      email = row?.status ?? null;
    }
  }
  return { ...r, email };
}

// supabase/stripe-webhook/index.ts
Deno.serve(createWebhookHandler(depsFromEnv((key) => Deno.env.get(key))));
