// Supabase Edge Function "stripe-webhook" — ONE FILE, ready to paste into the dashboard editor.
// GENERATED by scripts/build-dashboard-functions.mjs from supabase/functions/. Do not edit here:
// change the sources, run `npm run build:functions`, and paste the new file.
// Deploy: Supabase → Edge Functions → Deploy a new function → Via Editor → name it "stripe-webhook",
// replace the editor's contents with this whole file, deploy, then turn OFF "Verify JWT".
// Setup and secrets: supabase/SHOP.md.
// supabase/functions/_shared/db.ts
var DbError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
  }
  status;
};
function createDb(supabaseUrl, serviceKey, fetchFn = fetch) {
  const headers = { apikey: serviceKey, "Content-Type": "application/json" };
  if (serviceKey.startsWith("eyJ")) headers.Authorization = `Bearer ${serviceKey}`;
  const fail = async (res) => {
    let message = `db_${res.status}`;
    try {
      const body = await res.json();
      if (body && typeof body.message === "string") message = body.message;
    } catch {
    }
    return new DbError(message, res.status);
  };
  return {
    async rpc(name, args = {}) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/rpc/${name}`, { method: "POST", headers, body: JSON.stringify(args) });
      if (!res.ok) throw await fail(res);
      const text = await res.text();
      return text ? JSON.parse(text) : null;
    },
    async select(table, query) {
      const res = await fetchFn(`${supabaseUrl}/rest/v1/${table}?${query}`, { headers });
      if (!res.ok) throw await fail(res);
      return await res.json();
    }
  };
}
async function loadOrder(db, id) {
  if (!/^[0-9a-f-]{36}$/i.test(id)) return null;
  const rows = await db.select("shop_orders", `id=eq.${id}&select=*,shop_order_items(*)`);
  return rows[0] ?? null;
}

// supabase/functions/_shared/email.ts
function createResendMailer(opts) {
  const fetchFn = opts.fetch ?? fetch;
  return {
    configured: Boolean(opts.apiKey),
    async send(to, msg, idempotencyKey) {
      const res = await fetchFn("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${opts.apiKey}`,
          "Content-Type": "application/json",
          ...idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {}
        },
        body: JSON.stringify({ from: opts.from, to: [to], reply_to: opts.replyTo || void 0, subject: msg.subject, html: msg.html, text: msg.text })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.message ?? `resend_${res.status}`);
      return { id: data.id ?? "" };
    }
  };
}
var esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
var money = (cents) => `$${((cents ?? 0) / 100).toFixed(2)}`;
var orderLabel = (o) => o.order_number ? `#${o.order_number}` : "";
var firstName = (o) => (o.customer_name ?? o.shipping_name ?? "").trim().split(/\s+/)[0] ?? "";
function addressLines(name, a) {
  if (!a) return [];
  return [
    name ?? "",
    a.line1 ?? "",
    a.line2 ?? "",
    [a.city, [a.state, a.postal_code].filter(Boolean).join(" ")].filter(Boolean).join(", "),
    a.country && a.country !== "US" ? a.country : ""
  ].filter((l) => l.trim());
}
function trackingLink(carrier, tracking, explicit) {
  if (explicit && /^https:\/\//.test(explicit)) return explicit;
  if (!tracking) return null;
  const n = encodeURIComponent(tracking.replace(/\s+/g, ""));
  switch ((carrier ?? "").trim().toLowerCase()) {
    case "usps":
      return `https://tools.usps.com/go/TrackConfirmAction?tLabels=${n}`;
    case "ups":
      return `https://www.ups.com/track?tracknum=${n}`;
    case "fedex":
      return `https://www.fedex.com/fedextrack/?trknbr=${n}`;
    default:
      return null;
  }
}
var C = {
  page: "#fbf7f1",
  // cream
  card: "#ffffff",
  ink: "#3d3834",
  // warm charcoal (articles)
  soft: "#5c5550",
  muted: "#6e6461",
  rule: "#e7ddd4",
  accent: "#96666b",
  // rose-deep
  sage: "#f1f4ec",
  sageRule: "#dde4d3",
  rose: "#f8eeec",
  button: "#4a3f3e"
};
var SANS = "Montserrat,'Helvetica Neue',Helvetica,Arial,sans-serif";
var SERIF = "Georgia,'Times New Roman',serif";
var p = (text, style = "") => ({ html: `<p style="margin:0 0 16px;${style}">${esc(text)}</p>`, text });
var small = (text) => p(text, `font-size:13px;line-height:1.55;color:${C.muted}`);
var eyebrowStyle = `margin:0 0 10px;font-family:${SANS};font-size:11px;font-weight:700;letter-spacing:0.18em;text-transform:uppercase;color:${C.accent}`;
var heading = (text) => ({
  html: `<p style="${eyebrowStyle};margin-top:28px;color:${C.muted}">${esc(text)}</p>`,
  text: `
${text.toUpperCase()}`
});
var lines = (ls) => ({ html: `<p style="margin:0 0 16px">${ls.map(esc).join("<br>")}</p>`, text: ls.join("\n") });
var textLink = (label, href) => ({
  html: `<p style="margin:0 0 16px"><a href="${esc(href)}" style="color:${C.accent};font-weight:600;text-decoration:underline">${esc(label)}</a></p>`,
  text: `${label}: ${href}`
});
var button = (label, href) => ({
  html: `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:4px 0 18px"><tr><td bgcolor="${C.button}" style="border-radius:6px;background:${C.button}"><a href="${esc(href)}" style="display:inline-block;padding:13px 24px;font-family:${SANS};font-size:15px;font-weight:600;line-height:1.2;color:#ffffff;text-decoration:none;border-radius:6px">${esc(label)}</a></td></tr></table>`,
  text: `${label}: ${href}`
});
var panel = (bg, border, blocks) => ({
  html: `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 20px;border-collapse:separate"><tr><td bgcolor="${bg}" style="background:${bg};border:1px solid ${border};border-radius:8px;padding:20px 20px 6px">${blocks.map((b) => b.html).join("")}</td></tr></table>`,
  text: blocks.map((b) => b.text).join("\n")
});
var panelTitle = (text) => ({
  html: `<p style="margin:0 0 8px;font-family:${SERIF};font-size:19px;line-height:1.3;color:${C.ink}">${esc(text)}</p>`,
  text: `
${text}`
});
function splitName(name) {
  const m = name.match(/^(.*) \(([^()]+)\)$/);
  return m ? [m[1], m[2]] : [name, null];
}
var THUMBS = /* @__PURE__ */ new Set(["calendar-26-week", "calendar-52-week"]);
var thumb = (slug, siteUrl) => `${siteUrl}/email/${THUMBS.has(slug) ? slug : "calendar-26-week"}.jpg`;
function itemRows(o, siteUrl, withPrices) {
  const html = o.shop_order_items.map((i) => {
    const [name, edition] = splitName(i.product_name);
    return `<tr><td width="64" valign="top" style="padding:14px 14px 14px 0;border-bottom:1px solid ${C.rule}"><img src="${esc(thumb(i.product_slug, siteUrl))}" width="56" alt="" style="display:block;width:56px;height:auto;border:1px solid ${C.rule};border-radius:4px"></td><td valign="top" style="padding:14px 0;border-bottom:1px solid ${C.rule}"><p style="margin:0;font-weight:600;color:${C.ink}">${esc(name)}</p>` + (edition ? `<p style="margin:2px 0 0;font-size:14px;color:${C.soft}">${esc(edition)}</p>` : "") + `<p style="margin:4px 0 0;font-size:13px;color:${C.muted}">Qty ${i.quantity}${withPrices && i.quantity > 1 ? ` × ${money(i.unit_price_cents)}` : ""} · includes the cleaning companion website</p></td>` + (withPrices ? `<td valign="top" align="right" style="padding:14px 0 14px 12px;border-bottom:1px solid ${C.rule};white-space:nowrap;color:${C.ink}">${money(i.unit_price_cents * i.quantity)}</td>` : "") + `</tr>`;
  }).join("");
  return {
    html: `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;border-top:1px solid ${C.rule}">${html}</table>`,
    text: o.shop_order_items.map((i) => `${i.product_name} × ${i.quantity}${withPrices ? `: ${money(i.unit_price_cents * i.quantity)}` : ""}`).join("\n")
  };
}
function totals(o) {
  const rows = [["Subtotal", money(o.subtotal_cents)]];
  if (o.discount_cents) rows.push([o.promotion_code ? `Discount (${o.promotion_code})` : "Discount", `−${money(o.discount_cents)}`]);
  rows.push([o.shipping_method || "Shipping", o.shipping_cents ? money(o.shipping_cents) : "Free"]);
  if (o.tax_cents) rows.push(["Sales tax", money(o.tax_cents)]);
  rows.push(["Total paid", money(o.total_cents), true]);
  return {
    html: `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;margin:6px 0 20px">` + rows.map(
      ([a, b, strong]) => strong ? `<tr><td style="padding:12px 0 0;border-top:2px solid ${C.ink};font-family:${SERIF};font-size:18px;color:${C.ink}">${esc(a)}</td><td align="right" style="padding:12px 0 0;border-top:2px solid ${C.ink};font-family:${SERIF};font-size:18px;font-weight:700;color:${C.ink};white-space:nowrap">${esc(b)}</td></tr>` : `<tr><td style="padding:5px 0;font-size:14px;color:${C.soft}">${esc(a)}</td><td align="right" style="padding:5px 0;font-size:14px;color:${C.soft};white-space:nowrap">${esc(b)}</td></tr>`
    ).join("") + `</table>`,
    text: rows.map(([a, b]) => `${a}: ${b}`).join("\n")
  };
}
function companionPanel(siteUrl) {
  return panel(C.sage, C.sageRule, [
    panelTitle("Your cleaning companion"),
    p("Your calendar comes with the free cleaning companion website. Each day it shows a small Daily Reset and one area of the house to focus on, matching the cleaning zone printed on your calendar.", "font-size:15px"),
    button("Open the cleaning companion", `${siteUrl}/app`),
    small("Or scan the QR code printed on your calendar with your phone’s camera. No account, no subscription, nothing to install.")
  ]);
}
function layout(b, o, opts) {
  const test = o.livemode === false;
  const site = opts.siteUrl;
  const testBanner = test ? `<tr><td style="padding:0 0 14px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td bgcolor="${C.rose}" style="background:${C.rose};border:1px dashed ${C.accent};border-radius:8px;padding:12px 16px;font-family:${SANS};font-size:13px;line-height:1.5;color:${C.ink}"><strong style="letter-spacing:0.12em;text-transform:uppercase">Test order</strong> · Stripe test mode. No real payment was taken.</td></tr></table></td></tr>` : "";
  const support = opts.supportEmail ? `Questions about your order? Reply to this email or write to <a href="mailto:${esc(opts.supportEmail)}" style="color:${C.accent}">${esc(opts.supportEmail)}</a>.` : "Questions about your order? Reply to this email.";
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="supported-color-schemes" content="light"><title>${esc(b.subject)}</title></head>
<body style="margin:0;padding:0;background:${C.page};-webkit-text-size-adjust:100%">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all">${esc(b.preheader)}&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${C.page}" style="background:${C.page}"><tr><td align="center" style="padding:24px 12px 36px">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:560px">
<tr><td align="center" style="padding:4px 0 20px"><a href="${esc(site)}"><img src="${esc(site)}/email/omc-badge-144.png" width="72" height="72" alt="Organized Mom Collective" style="display:block;width:72px;height:72px;border:0"></a></td></tr>
${testBanner}
<tr><td bgcolor="${C.card}" style="background:${C.card};border:1px solid ${C.rule};border-radius:10px;padding:32px 24px 16px;font-family:${SANS};font-size:16px;line-height:1.6;color:${C.ink}">
<p style="${eyebrowStyle}">${esc(b.eyebrow)}</p>
<h1 style="margin:0 0 18px;font-family:${SERIF};font-size:27px;line-height:1.25;font-weight:700;color:${C.ink}">${esc(b.title)}</h1>
${b.blocks.map((x) => x.html).join("\n")}
</td></tr>
<tr><td align="center" style="padding:24px 12px 0;font-family:${SANS};font-size:13px;line-height:1.6;color:${C.muted}">
<p style="margin:0 0 10px">${support}</p>
<p style="margin:0">Organized Mom Collective · <a href="${esc(site)}" style="color:${C.muted}">organizedmomcollective.com</a></p>
${test ? `<p style="margin:10px 0 0">This is a test email from a test-mode order.</p>` : ""}
</td></tr>
</table></td></tr></table></body></html>`;
  const text = [
    ...test ? ["[TEST ORDER: Stripe test mode. No real payment was taken.]", ""] : [],
    b.eyebrow.toUpperCase(),
    b.title,
    "",
    ...b.blocks.map((x) => x.text),
    "",
    opts.supportEmail ? `Questions about your order? Reply to this email or write to ${opts.supportEmail}.` : "Questions about your order? Reply to this email.",
    `Organized Mom Collective · ${site}`
  ].join("\n");
  return { subject: test ? `[Test] ${b.subject}` : b.subject, html, text };
}
function renderEmail(kind, o, opts) {
  return layout(renderBody(kind, o, opts), o, opts);
}
function renderBody(kind, o, opts) {
  const n = orderLabel(o);
  const hi = firstName(o);
  const ship = addressLines(o.shipping_name, o.shipping_address);
  const shipTo = ship.length ? [heading("Shipping to"), lines(ship)] : [];
  switch (kind) {
    case "confirmation":
      return {
        subject: `Your Organized Mom Collective order ${n}`,
        preheader: `Order ${n} · ${money(o.total_cents)} paid. We’ll email your tracking number when it ships.`,
        eyebrow: `Order ${n} confirmed`,
        title: hi ? `Thank you, ${hi}.` : "Thank you for your order.",
        blocks: [
          p("Your order is confirmed, and this email is your receipt. We pack each order by hand and will email you the tracking number as soon as it ships."),
          heading("Your order"),
          itemRows(o, opts.siteUrl, true),
          totals(o),
          ...shipTo,
          companionPanel(opts.siteUrl)
        ]
      };
    case "shipped": {
      const url = trackingLink(o.carrier, o.tracking_number, o.tracking_url);
      return {
        subject: `Your order ${n} has shipped`,
        preheader: `${o.carrier ?? "Your package"}${o.tracking_number ? ` · tracking ${o.tracking_number}` : ""}`,
        eyebrow: `Order ${n} shipped`,
        title: "Your order is on its way",
        blocks: [
          p(hi ? `Good news, ${hi}: your calendar has shipped.` : "Good news: your calendar has shipped."),
          panel(C.page, C.rule, [
            ...o.carrier ? [p(`Carrier: ${o.carrier}`, "margin:0 0 4px;font-size:15px")] : [],
            ...o.tracking_number ? [p(`Tracking number: ${o.tracking_number}`, "margin:0 0 14px;font-size:15px;font-weight:600;word-break:break-all")] : [],
            ...url ? [button("Track your package", url)] : [small("Use the tracking number on the carrier’s website.")]
          ]),
          small("It can take a day for the first tracking update to appear."),
          ...shipTo,
          heading("In this package"),
          itemRows(o, opts.siteUrl, false),
          p(""),
          companionPanel(opts.siteUrl)
        ]
      };
    }
    case "refund": {
      const full = o.payment_status === "refunded";
      const canceled = full && o.fulfillment_status === "canceled";
      const amount = opts.refundCents ?? o.refunded_cents;
      return {
        subject: canceled ? `Order ${n} canceled and refunded` : `Refund for order ${n}`,
        preheader: `${money(canceled ? o.refunded_cents : amount)} is on its way back to your original payment method.`,
        eyebrow: canceled ? `Order ${n} canceled` : `Order ${n} refund`,
        title: canceled ? "Your order has been canceled" : "Your refund is on its way",
        blocks: [
          ...canceled ? [p("Your order has been canceled and won’t be shipped. You’ve been refunded in full.")] : [],
          panel(C.page, C.rule, [
            p("Refunded", `margin:0;font-size:12px;font-weight:700;letter-spacing:0.16em;text-transform:uppercase;color:${C.muted}`),
            p(money(canceled ? o.refunded_cents : amount), `margin:2px 0 6px;font-family:${SERIF};font-size:30px;line-height:1.2;color:${C.ink}`),
            p(
              `To your original payment method.${!canceled && o.refunded_cents !== amount ? ` Total refunded on this order: ${money(o.refunded_cents)} of ${money(o.total_cents)}.` : ""}`,
              `font-size:14px;color:${C.soft}`
            )
          ]),
          p("Refunds usually take 5–10 business days to appear, depending on your bank.")
        ]
      };
    }
    case "access":
      return {
        subject: "Your cleaning companion: how to get started",
        preheader: "Open it from this email or scan the QR code on your calendar. No account, no subscription.",
        eyebrow: "Your cleaning companion",
        title: "How to use your cleaning companion",
        blocks: [
          p(hi ? `Hi ${hi}, here’s how to open the cleaning companion website that comes with your calendar.` : "Here’s how to open the cleaning companion website that comes with your calendar."),
          button("Open the cleaning companion", `${opts.siteUrl}/app`),
          lines([
            "1. Open it with the button above, or scan the QR code printed on your calendar with your phone’s camera.",
            "2. It opens on Today: a small Daily Reset and one area of the house to focus on.",
            "3. Check things off as you go. Your checkmarks are saved in your phone’s browser.",
            "4. To keep it handy, add it to your Home Screen from Settings."
          ]),
          p("It’s free with your calendar. No account, no subscription, nothing to install."),
          textLink("See how it works", `${opts.siteUrl}/companion`)
        ]
      };
  }
}
async function sha256Hex(text) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function deliverEmail(deps, orderId, kind, key, extra = {}) {
  try {
    const order = await loadOrder(deps.db, orderId);
    if (!order?.email) return "no_email";
    const claim = await deps.db.rpc("shop_email_claim", { p_order: orderId, p_kind: kind, p_key: key, p_to: order.email });
    if (claim == null) return "duplicate";
    if (!deps.mailer.configured) {
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "skipped", p_provider_id: null, p_error: "Email provider not configured" });
      return "skipped";
    }
    try {
      const msg = renderEmail(kind, order, { siteUrl: deps.siteUrl, supportEmail: deps.supportEmail, ...extra });
      const idem = `${key}/${(await sha256Hex(`${order.email}
${msg.subject}
${msg.text}`)).slice(0, 24)}`;
      const { id } = await deps.mailer.send(order.email, msg, idem.slice(0, 256));
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "sent", p_provider_id: id, p_error: null });
      return "sent";
    } catch (err) {
      await deps.db.rpc("shop_email_result", { p_id: claim, p_status: "failed", p_provider_id: null, p_error: err.message });
      return "failed";
    }
  } catch (err) {
    console.error("email", kind, orderId, err);
    return "failed";
  }
}

// supabase/functions/_shared/env.ts
var STRIPE_API_VERSION = "2025-03-31.basil";
function readEnv(get) {
  const v = (k, fallback = "") => (get(k) ?? fallback).trim();
  const siteUrl = v("SHOP_SITE_URL", "https://organizedmomcollective.com").replace(/\/$/, "");
  const origins = v("SHOP_ALLOWED_ORIGINS");
  return {
    supabaseUrl: v("SUPABASE_URL").replace(/\/$/, ""),
    serviceRoleKey: v("SUPABASE_SERVICE_ROLE_KEY"),
    anonKey: v("SUPABASE_ANON_KEY"),
    stripeSecretKey: v("STRIPE_SECRET_KEY"),
    stripeWebhookSecret: v("STRIPE_WEBHOOK_SECRET"),
    liveCheckoutEnabled: v("SHOP_LIVE_CHECKOUT") === "enabled",
    siteUrl,
    allowedOrigins: origins ? origins.split(",").map((o) => o.trim().replace(/\/$/, "")).filter(Boolean) : [siteUrl],
    previewToken: v("SHOP_PREVIEW_TOKEN"),
    resendApiKey: v("RESEND_API_KEY"),
    emailFrom: v("SHOP_EMAIL_FROM", "Organized Mom Collective <orders@organizedmomcollective.com>"),
    emailReplyTo: v("SHOP_EMAIL_REPLY_TO")
  };
}

// supabase/functions/_shared/http.ts
function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", ...headers }
  });
}
function safeEqual(a, b) {
  const enc = new TextEncoder();
  const x = enc.encode(a);
  const y = enc.encode(b);
  let diff = x.length ^ y.length;
  for (let i = 0; i < Math.max(x.length, y.length); i++) diff |= (x[i] ?? 0) ^ (y[i] ?? 0);
  return diff === 0;
}

// supabase/functions/_shared/stripe.ts
function stripeMode(key) {
  return /^(sk|rk)_live_/.test(key) ? "live" : "test";
}
var StripeError = class extends Error {
  constructor(message, status, code) {
    super(message);
    this.status = status;
    this.code = code;
  }
  status;
  code;
};
function formEncode(params) {
  const out = new URLSearchParams();
  const add = (key, value) => {
    if (value === null || value === void 0) return;
    if (Array.isArray(value)) value.forEach((v, i) => add(`${key}[${i}]`, v));
    else if (typeof value === "object") for (const [k, v] of Object.entries(value)) add(`${key}[${k}]`, v);
    else out.append(key, String(value));
  };
  for (const [k, v] of Object.entries(params)) add(k, v);
  return out.toString();
}
function createStripe(opts) {
  const base = opts.apiBase ?? "https://api.stripe.com";
  const fetchFn = opts.fetch ?? fetch;
  return {
    mode: stripeMode(opts.secretKey),
    async request(method, path, params = {}, idempotencyKey) {
      const body = formEncode(params);
      const headers = {
        Authorization: `Bearer ${opts.secretKey}`,
        "Stripe-Version": opts.apiVersion
      };
      if (method === "POST") headers["Content-Type"] = "application/x-www-form-urlencoded";
      if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
      const url = method === "GET" && body ? `${base}${path}?${body}` : `${base}${path}`;
      const res = await fetchFn(url, { method, headers, body: method === "POST" ? body : void 0 });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        const err = data.error;
        throw new StripeError(err?.message ?? `stripe_${res.status}`, res.status, err?.code);
      }
      return data;
    }
  };
}
async function hmacHex(secret, payload) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(payload));
  return [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function verifyStripeSignature(payload, header, secret, nowSeconds = Math.floor(Date.now() / 1e3), toleranceSeconds = 300) {
  if (!header || !secret) return false;
  const parts = header.split(",").map((p2) => p2.split("="));
  const t = Number(parts.find(([k]) => k === "t")?.[1]);
  const v1 = parts.filter(([k]) => k === "v1").map(([, v]) => v);
  if (!Number.isFinite(t) || v1.length === 0) return false;
  if (Math.abs(nowSeconds - t) > toleranceSeconds) return false;
  const expected = await hmacHex(secret, `${t}.${payload}`);
  return v1.some((sig) => safeEqual(sig, expected));
}

// supabase/functions/_shared/deps.ts
function depsFromEnv(get, fetchFn = fetch) {
  const env = readEnv(get);
  return {
    env,
    db: createDb(env.supabaseUrl, env.serviceRoleKey, fetchFn),
    stripe: createStripe({ secretKey: env.stripeSecretKey, apiVersion: STRIPE_API_VERSION, fetch: fetchFn }),
    mailer: createResendMailer({ apiKey: env.resendApiKey, from: env.emailFrom, replyTo: env.emailReplyTo, fetch: fetchFn }),
    fetch: fetchFn,
    now: () => Math.floor(Date.now() / 1e3)
  };
}
function stripeBlockedReason(deps) {
  if (!deps.env.stripeSecretKey) return "stripe_not_configured";
  if (!/^(sk|rk)_(test|live)_/.test(deps.env.stripeSecretKey)) return "stripe_not_configured";
  if (deps.stripe.mode === "live" && !deps.env.liveCheckoutEnabled) return "live_checkout_disabled";
  return null;
}
var emailDeps = (deps) => ({
  db: deps.db,
  mailer: deps.mailer,
  siteUrl: deps.env.siteUrl,
  supportEmail: deps.env.emailReplyTo
});

// supabase/functions/_shared/checkout.ts
var isPaidSession = (s) => s.status === "complete" && (s.payment_status === "paid" || s.payment_status === "no_payment_required");
function promotionLabel(s) {
  const d = s.total_details?.breakdown?.discounts?.[0]?.discount;
  if (!d) return null;
  const promo = d.promotion_code;
  if (promo && typeof promo === "object" && promo.code) return promo.code;
  const coupon = d.coupon ?? d.source?.coupon;
  if (coupon && typeof coupon === "object") return coupon.name ?? coupon.id ?? null;
  if (typeof promo === "string") return promo;
  return typeof coupon === "string" ? coupon : null;
}
function paidOrderData(s) {
  const ship = s.collected_information?.shipping_details ?? s.shipping_details ?? null;
  const pi = typeof s.payment_intent === "string" ? s.payment_intent : s.payment_intent?.id ?? null;
  const rate = s.shipping_cost?.shipping_rate;
  const t = s.total_details ?? {};
  return {
    order_id: s.metadata?.order_id ?? s.client_reference_id ?? null,
    payment_intent: pi,
    livemode: Boolean(s.livemode),
    email: s.customer_details?.email ?? null,
    name: s.customer_details?.name ?? null,
    phone: s.customer_details?.phone ?? null,
    shipping_name: ship?.name ?? s.customer_details?.name ?? null,
    shipping_address: ship?.address ?? null,
    shipping_method: rate && typeof rate === "object" ? rate.display_name ?? null : null,
    promotion_code: promotionLabel(s),
    currency: s.currency ?? null,
    subtotal_cents: s.amount_subtotal ?? null,
    discount_cents: t.amount_discount ?? 0,
    shipping_cents: t.amount_shipping ?? s.shipping_cost?.amount_total ?? 0,
    tax_cents: t.amount_tax ?? 0,
    total_cents: s.amount_total ?? null
  };
}

// supabase/functions/_shared/handlers/webhook.ts
function createWebhookHandler(deps) {
  return async (req) => {
    if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
    const raw = await req.text();
    const valid = await verifyStripeSignature(raw, req.headers.get("stripe-signature"), deps.env.stripeWebhookSecret, deps.now());
    if (!valid) return json({ error: "invalid_signature" }, 400);
    let event;
    try {
      event = JSON.parse(raw);
    } catch {
      return json({ error: "invalid_payload" }, 400);
    }
    const blocked = stripeBlockedReason(deps);
    if (blocked) return json({ error: blocked }, 503);
    if (event.livemode !== (deps.stripe.mode === "live")) return json({ error: "mode_mismatch" }, 400);
    const state = await deps.db.rpc("shop_stripe_event_begin", { p_id: event.id, p_type: event.type });
    if (state === "done") return json({ received: true, duplicate: true });
    try {
      await handleEvent(deps, event);
      await deps.db.rpc("shop_stripe_event_done", { p_id: event.id });
      return json({ received: true });
    } catch (err) {
      console.error("stripe-webhook", event.type, event.id, err);
      return json({ error: "processing_failed" }, 500);
    }
  };
}
var idOf = (v) => typeof v === "string" ? v : v && typeof v === "object" && "id" in v ? String(v.id) : null;
async function handleEvent(deps, event) {
  const obj = event.data.object;
  if (event.type.startsWith("checkout.session.") && !/^cs_(test|live)_[A-Za-z0-9]{10,200}$/.test(String(obj.id))) return;
  switch (event.type) {
    case "checkout.session.completed":
    case "checkout.session.async_payment_succeeded": {
      const session = await deps.stripe.request("GET", `/v1/checkout/sessions/${obj.id}`, {
        expand: ["shipping_cost.shipping_rate", "total_details.breakdown"]
      });
      if (!isPaidSession(session)) return;
      const r = await deps.db.rpc("shop_mark_paid", { p_session: session.id, p: paidOrderData(session) });
      if (!r.found) {
        console.warn("stripe-webhook: paid session with no order", session.id);
        return;
      }
      await deliverEmail(emailDeps(deps), r.order_id, "confirmation", `confirmation:${r.order_id}`);
      return;
    }
    case "checkout.session.async_payment_failed":
    case "checkout.session.expired": {
      await deps.db.rpc("shop_checkout_ended", {
        p_session: obj.id,
        p_status: event.type === "checkout.session.expired" ? "expired" : "failed",
        p_detail: { event: event.id }
      });
      return;
    }
    case "payment_intent.payment_failed": {
      const err = obj.last_payment_error ?? {};
      await deps.db.rpc("shop_note_event", {
        p_order: obj.metadata?.order_id ?? null,
        p_payment_intent: obj.id,
        p_kind: "payment_failed",
        p_detail: { message: err.message ?? null, code: err.code ?? null, decline_code: err.decline_code ?? null },
        p_flag: null
      });
      return;
    }
    case "charge.refunded": {
      const pi = idOf(obj.payment_intent);
      if (!pi) return;
      await applyRefund(deps, pi, Number(obj.amount_refunded ?? 0), "stripe");
      return;
    }
    case "refund.failed": {
      await deps.db.rpc("shop_note_event", {
        p_order: obj.metadata?.order_id ?? null,
        p_payment_intent: idOf(obj.payment_intent),
        p_kind: "refund_failed",
        p_detail: { amount_cents: obj.amount ?? null, reason: obj.failure_reason ?? null },
        p_flag: "refund_failed"
      });
      return;
    }
    case "charge.dispute.created": {
      await deps.db.rpc("shop_note_event", {
        p_order: null,
        p_payment_intent: idOf(obj.payment_intent),
        p_kind: "dispute_opened",
        p_detail: { amount_cents: obj.amount ?? null, reason: obj.reason ?? null },
        p_flag: "disputed"
      });
      return;
    }
    default:
      return;
  }
}
async function applyRefund(deps, paymentIntent, refundedTotal, actor) {
  const r = await deps.db.rpc("shop_apply_refund", {
    p_payment_intent: paymentIntent,
    p_refunded_cents: refundedTotal,
    p_actor: actor
  });
  let email = null;
  if (r.found && r.order_id) {
    const key = `refund:${r.order_id}:${refundedTotal}`;
    if (r.transitioned) {
      email = await deliverEmail(emailDeps(deps), r.order_id, "refund", key, { refundCents: r.amount_cents });
    } else {
      const [row] = await deps.db.select("shop_email_log", `dedupe_key=eq.${encodeURIComponent(key)}&select=status`);
      email = row?.status ?? null;
    }
  }
  return { ...r, email };
}

// supabase/stripe-webhook/index.ts
Deno.serve(createWebhookHandler(depsFromEnv((key) => Deno.env.get(key))));
